openapi: 3.0.0
info:
  title: 'Documentación realizado con Swagger, servicios funcionando con Laravel'
  description: 'Proyecto para la comunicación REST'
  contact:
    name: 'Correo de contacto'
    email: admin@admin.com
  license:
    name: 'Apache 2.0'
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  version: '1.0'
servers:
  -
    url: 'http://127.0.0.1:8000'
paths:
  /api/v1/ecssa/precios:
    get:
      tags:
        - Precios
      summary: 'Muestra todos los precios de los diferentes productos'
      description: 'Retorna todos lo registros de precios almacenados en la Base de Datos'
      operationId: getPrecios
      responses:
        200:
          description: 'Respuesta correcta'
          content:
            application/json: []
        401:
          description: 'No autenticado'
        403:
          description: 'Permisos denegados'
        400:
          description: 'Solicitud incorrecta'
        404:
          description: 'Servicio no encontrado'
      security:
        -
          passport: []
  /api/v1/ecssa/productos:
    get:
      tags:
        - Productos
      summary: 'Muestra todos los productos existentes'
      description: 'Retorna todos los registros de productos almacenados en la Base de Datos'
      operationId: getProductos
      responses:
        200:
          description: 'Respuesta correcta'
          content:
            application/json: []
        401:
          description: 'No autenticado'
        403:
          description: 'Permisos denegados'
        400:
          description: 'Solicitud incorrecta'
        404:
          description: 'Servicio no encontrado'
      security:
        -
          passport: []
security:
  - []
